"""State definition for the Deep Research Agent."""

from typing import Annotated, NotRequired, TypedDict

from langgraph.graph import add_messages


class AgentState(TypedDict):
    """State that flows through every node in the research graph.

    Fields:
        query: The original user research question.
        messages: Conversation history managed by LangGraph's add_messages reducer.
                  User input arrives here and the final report is appended as an
                  assistant message.
        search_queries: Accumulated list of search strings generated by the
                        query analyzer and synthesizer nodes.
        search_results: Mapping of search query -> list of result dicts.
                        Each result contains title, url, and content.
        iterations: How many search-synthesize cycles have completed so far.
        max_iterations: Upper bound on research cycles to prevent runaway loops.
        draft_report: Intermediate report text (used between iterations).
        final_report: The finished, citation-rich report returned to the user.
        sources: Deduplicated list of source dicts (id, title, url) referenced
                 in the final report.
        research_complete: Flag set by the synthesizer when coverage is
                           sufficient or max_iterations is reached.
    """

    query: str
    messages: Annotated[list, add_messages]
    search_queries: list[str]
    search_results: dict
    iterations: int
    max_iterations: int
    draft_report: NotRequired[str | None]
    final_report: NotRequired[str | None]
    sources: list[dict]
    research_complete: NotRequired[bool]
